const lessons = [
    {
        "id": "1",
        "title": "Вступ до фаху",
        "href1": "http://tam.vntu.edu.ua/images/%D0%9D%D0%9F_%D0%92%D0%A1%D0%A2%D0%A3%D0%9F_2016.PDF",
        "href2": "http://burennikov.vk.vntu.edu.ua/navch",
        "href3": "",
        "Dform": "( ДФН )",
        "Zform": "",
    },
    {
        "id": "2",
        "title": "Взаємозамінність, стандартизація та технічні вимірювання",
        "href1": "http://tam.vntu.edu.ua/images/%D0%9D%D0%9F_%D0%92%D0%A1%D0%A2%D0%92.PDF",
        "href2": "http://savulyakv.vk.vntu.edu.ua/stud",
        "href3": "http://semichasnova.vk.vntu.edu.ua/",
        "Dform": "( ДФН, ",
        "Zform": " ЗФН )",
    },
    {
        "id": "3",
        "title": "Гідравліка, гідро- та пневмоприводи",
        "href1": "http://repinskiy.vk.vntu.edu.ua/file/GGPP/72c545c7f6e78b2ce9cbee54a6cd97e6.pdf",
        "href2": "http://burennikov.vk.vntu.edu.ua/navch",
        "href3": "http://repinskiy.vk.vntu.edu.ua/navch",
        "Dform": "( ДФН, ",
        "Zform": " ЗФН )",
    },
    {
        "id": "4",
        "title": "Гідравліка і гідропневмоавтоматика",
        "href1": "http://tam.vntu.edu.ua/images/%D0%9D%D0%9F%D0%94_%D0%93i%D0%93%D0%9FA.PDF",
        "href2": "http://burennikov.vk.vntu.edu.ua/navch",
        "href3": "http://repinskiy.vk.vntu.edu.ua/navch",
        "Dform": "( ДФН, ",
        "Zform": " ЗФН )",
    },
    {
        "id": "5",
        "title": "Дискретні системи керування та мікропроцесорна техніка",
        "href1": "http://tam.vntu.edu.ua/images/%D0%9D%D0%9F_%D0%94%D0%B8%D1%81%D0%BA%D1%80-%D1%81%D0%B8%D1%81%D1%82-%D0%BA%D0%B5%D1%80%D1%83%D0%B2.PDF",
        "href2": "http://kozlov.vk.vntu.edu.ua/navch",
        "href3": "http://kozlov.vk.vntu.edu.ua/navch",
        "Dform": "( ДФН, ",
        "Zform": " ЗФН )",
    },
    {
        "id": "6",
        "title": "Інформатика",
        "href1": "http://tam.vntu.edu.ua/images/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%9D%D0%9F1_(2016).PDF",
        "href2": "http://savulyakv.vk.vntu.edu.ua/",
        "href3": "http://semichasnova.vk.vntu.edu.ua/",
        "Dform": "( ДФН, ",
        "Zform": " ЗФН )",
    },
    {
        "id": "7",
        "title": "Механоскладальні дільниці та цехи в машинобудуванні",
        "href1": "http://tam.vntu.edu.ua/images/NPD%D0%9C%D0%A1%D0%94%D0%A6.PDF",
        "href2": "http://serdyuk.vk.vntu.edu.ua/",
        "href3": "http://serdyuk.vk.vntu.edu.ua/",
        "Dform": "( ДФН, ",
        "Zform": " ЗФН )",
    },
    {
        "id": "8",
        "title": "Нові матеріали та композити",
        "href1": "http://tam.vntu.edu.ua/images/%D0%9D%D0%9F%D0%94_%D0%9D%D0%9C%D1%82%D0%B0%D0%9A_Word.PDF",
        "href2": "http://sukhorukov.vk.vntu.edu.ua/",
        "href3": "http://sukhorukov.vk.vntu.edu.ua/",
        "Dform": "( ДФН, ",
        "Zform": " ЗФН )",
    },
    {
        "id": "9",
        "title": "Основи автоматизації виробництва",
        "href1": "",
        "href2": "http://mulyar.vk.vntu.edu.ua/navch",
        "href3": "http://sukhorukov.vk.vntu.edu.ua/",
        "Dform": "( ДФН, ",
        "Zform": " ЗФН )",
    },
    {
        "id": "10",
        "title": "Основи взаємозамінності",
        "href1": "",
        "href2": "http://savulyakv.vk.vntu.edu.ua/stud",
        "href3": "",
        "Dform": "( ДФН )",
        "Zform": "",
    },
    {
        "id": "11",
        "title": "Основи науково-дослідної роботи",
        "href1": "http://tam.vntu.edu.ua/images/%D0%9D%D0%9F_%D0%9E%D0%9D%D0%94%D0%A0_0_(2).PDF",
        "href2": "http://semichasnova.vk.vntu.edu.ua/navch",
        "href3": "",
        "Dform": "( ДФН )",
        "Zform": "",
    },
    {
        "id": "12",
        "title": "Основи автоматизованого проектування",
        "href1": "http://tam.vntu.edu.ua/images/%D0%9E%D0%90%D0%9F_2013_%D0%9D%D0%9F.pdf",
        "href2": "http://petrov.vk.vntu.edu.ua/stud",
        "href3": "http://petrov.vk.vntu.edu.ua/stud",
        "Dform": "( ДФН, ",
        "Zform": " ЗФН )",
    },
    {
        "id": "13",
        "title": "Основи технології машинобудування",
        "href1": "http://tam.vntu.edu.ua/images/%D0%9D%D0%9F_%D0%9E%D0%A2%D0%9C_2012.PDF",
        "href2": "http://deribo.vk.vntu.edu.ua/navch",
        "href3": "http://sukhorukov.vk.vntu.edu.ua/navch",
        "Dform": "( ДФН, ",
        "Zform": " ЗФН )",
    },
    {
        "id": "14",
        "title": "Проектування та виробництво заготовок деталей машин",
        "href1": "http://tam.vntu.edu.ua/images/NPD%D0%9F%D0%92%D0%97%D0%94%D0%9C.PDF",
        "href2": "http://lozinskyi.vk.vntu.edu.ua/navch",
        "href3": "http://lozinskyi.vk.vntu.edu.ua/navch",
        "Dform": "( ДФН, ",
        "Zform": " ЗФН )",
    },
    {
        "id": "15",
        "title": "Технологічні основи машинобдування",
        "href1": "",
        "href2": "http://lozinskyi.vk.vntu.edu.ua/navch",
        "href3": "http://lozinskyi.vk.vntu.edu.ua/navch",
        "Dform": "( ДФН, ",
        "Zform": " ЗФН )",
    },
    {
        "id": "16",
        "title": "Технологічна оснастка",
        "href1": "http://tam.vntu.edu.ua/images/%D0%A2%D0%9E_2013_%D0%9D%D0%9F.pdf",
        "href2": "http://petrov.vk.vntu.edu.ua/stud",
        "href3": "http://petrov.vk.vntu.edu.ua/stud",
        "Dform": "( ДФН, ",
        "Zform": " ЗФН )",
    },
    {
        "id": "17",
        "title": "Технології та верстати з ЧПК",
        "href1": "http://tam.vntu.edu.ua/images/ТтаВзЧПК.PDF",
        "href2": "http://deribo.vk.vntu.edu.ua/navch",
        "href3": "http://serdyuk.vk.vntu.edu.ua/navch",
        "Dform": "( ДФН, ",
        "Zform": " ЗФН )",
    },
    {
        "id": "18",
        "title": "Технологія машинобудування",
        "href1": "http://tam.vntu.edu.ua/images/%D0%9D%D0%9F_%D0%A2%D0%9C_2013.PDF",
        "href2": "http://deribo.vk.vntu.edu.ua/",
        "href3": "http://deribo.vk.vntu.edu.ua/",
        "Dform": "( ДФН, ",
        "Zform": " ЗФН )",
    },

]
export default lessons;


